schema = 2

[package]
id = "rintawa.rtwkit.web-ui"
name = "rtwKit Web UI"
version = "0.0.7"
replaces = ["rintawa.web-ui"]
description = "Default web UI layer for Rintawa"
license = "GPL-3.0-only"

[[package.dependencies]]
id = "rintawa.rtwkit.web-runtime"
requirement = ">=0.0.1, <0.1.0"

[build]
artifact-root = "build/rtw"
command = ["bash", "build.sh"]
