id = "rintawa.rtwkit.web-ui"
name = "rtwKit Web UI"
version = "0.0.7"
sdk = "^0.0"

[[components]]
id = "web"
kind = "ui"
target = "rintawa.runtime.web-bundle@1"
entry = "web-layer.toml"
required = true

[components.permissions]
runtime = ["asset-import", "background-task", "loopback-listen", "user-resource-import"]
