id = "rintawa.world-manager"
name = "World Manager"
version = "0.0.1"
sdk = "^0.0"

[[components]]
id = "runtime"
kind = "runtime"
target = "rintawa.runtime.wasm-component@1"
entry = "runtime.wasm"
required = true

[components.permissions]
runtime = ["world-session-read", "world-session-write"]
